### ISSUE TITLE
Accessing Hubot

### ISSUE THREAD

**Issue by dav92lee** [hubot-scripts/hubot-heroku-keepalive#14]
I was hoping that you could help me understand your hubot heroku keepalive script a little better.  I am struggling to have my hubot wake up during a sleep period (or verifying if your plugin is working at all) -- specifically, i'm not sure what you mean by "accessing your Hubot during a sleep period will wake it, but it will return to sleep after 30 minutes".  Does "accessing my hubot" mean simply chatting to it -- because that has not been working for me.

**Comment by chrisvfritz** [comment]
"Accessing your Hubot" just means pinging it, which you can do on the command line in your project folder with:

```
curl $(heroku apps:info -s | grep web-url | cut -d= -f2)
```

**Comment by technicalpickles** [comment]
To be more specific, 'accessing your hubot' means accessing it over HTTP, not chatting with it.

> Does "accessing my hubot" mean simply chatting to it -- because that has not been working for me.

Basically, this script works by pinging itself over HTTP during it's 'waking hours' (as described and configured in the README). When it gets to the sleeping hours, it stops being pinged, and so will go to sleep. At that point, the bot will stop responding in chat.

If something else 'accesses' it over HTTP, it will wake up and respond again in chat, but will count against your hour quota.

You'll need something external to hubot to wake it up after it's gone to sleep. The README suggests using the Heroku Scheduler for that. I suspect that's the step you are missing.

**Comment by jonathan-soifer** [comment]
Is this:

```
date T22:32:14.135607+00:00 app[web.1]: [datestamp (BRST)] INFO Skipping keep alive, time to rest
date T22:32:14.134233+00:00 app[web.1]: [datestamp (BRST)] INFO keepalive ping
date T22:37:14.144172+00:00 app[web.1]: [datestamp (BRST)] INFO Skipping keep alive, time to rest
date T22:37:14.144073+00:00 app[web.1]: [datestamp (BRST)] INFO keepalive ping
```

Expected?

Is it skipping the keep alive or is it pinging?

**Comment by technicalpickles** [comment]
@jonathan-soifer that's pretty weird. The [logic is here](https://github.com/hubot-scripts/hubot-heroku-keepalive/blob/master/src/heroku-keepalive.coffee#L57-L65) but it looks like it's not correctly knowing when to wake & rest. I'd try 1.0.1 which I just released to see if it helps. Can you open a new issue if you still see problems like that?

I think the original question was answered, so going to close for now.
