### ISSUE TITLE
Can't set night owl schedule

### ISSUE THREAD

**Issue by brownbro** [hubot-scripts/hubot-heroku-keepalive#17]
I set the environment variables as follows
- `HUBOT_HEROKU_WAKEUP_TIME = '8:00'`
- `HUBOT_HEROKU_SLEEP_TIME = '2:00'`

but hubot puts `INFO Skipping keep alive, time to rest` log out and sleeps soon.
(I think [this line](https://github.com/hubot-scripts/hubot-heroku-keepalive/blob/master/src/heroku-keepalive.coffee#L57) decides the behavior.)

Does anyone know the way to avoid this problem?

**Comment by kamui** [comment]
I'm having the same issue setting it for the same time range.

**Comment by mmeester** [comment]
try setting it to sleep before midnight 23:59 and you're problem is solved for now...

**Comment by kamui** [comment]
`26:00` works too.

**Comment by brownbro** [comment]
@kamui @mmeester thanks for your advises.
I tried `23:59` and  `26:00`, then my hubot slept around 0:30 (without any other stimulus/access).
It wan't able to be awake until 2:00.

**Comment by brownbro** [comment]
:+1:

**Comment by beck** [comment]
:star:

**Comment by travi** [comment]
Any update on this? I'm seeing this problem as well.

**Comment by technicalpickles** [comment]
This is fixed in 1.0.1

**Comment by brownbro** [comment]
Thanks @treby @technicalpickles

**Comment by treby** [comment]
:yellow_heart:
