### ISSUE TITLE
Keep alive URL with scheduler... is it literally that {env_var} inside?

### ISSUE THREAD

**Issue by dylanh724** [hubot-scripts/hubot-heroku-keepalive#27]
Will heroku accept the env var? or should I put the actual one?
Still a trailing slash/ if manual, right?
http or https?

Sorry dumb questions, but my keepalive isn't working

**Comment by dylanh724** [comment]
i think i resolved it .. took off httpS and just did http.

**Comment by treby** [comment]
Sorry for late.
Since it seems already solved, I'll close this issue.
