### ISSUE TITLE
heroku: command not found

### ISSUE THREAD

**Issue by DengkeDu** [hubot-scripts/hubot-heroku-keepalive#31]
In hubot project repository, I run `npm install hubot-heroku-keepalive --save` , and add the `hubot-heroku-keepalive` to my external-scripts.json, there exists hubot-heroku-keepalive under node_modules directory, but when run `heroku apps:info` , it said `heroku: command not found`, why? Thanks!

**Comment by treby** [comment]
may be you should install heroku toolbelt.
